### ISSUE TITLE
Incorrect measurements

### ISSUE THREAD

**Issue by CrackXT** [adafruit/Adafruit-128x32-I2C-OLED-Breakout-PCB#5]
Some of the dimensions of the technical drawing are not correct!

Adafruit OLED 128x32 Mono I2C STEMMA QT rev B

It's 0.85x1.30inch and not 0.86x1x30inch, also on the website (shop) there are incorrect information (0.80x1.40inch?).

https://www.adafruit.com/product/4440

Kind regards
CrackXT

**Comment by kattni** [comment]
Updated. The dimension in the board file was associated with an incorrect board element. This has been fixed.
